name: Gaurav Nawathey
favicon: null
layout_spectrum: 0.6744864068459719
typography_spectrum: 0.1891280459240079
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9728602520190179
  lightness: 0.6207208619453013
  saturation: 0.7100660142023116
  rhythmicContrast: 0.41716296318918467
purpose: []
