analytics: {}
color:
  brandColors:
    - '#0c0c0c'
    - '#ffe4b3'
    - '#c6af59'
    - '#836c48'
    - '#d8682a'
  brandStrength: 1
  lightness: 0.75
  rhythmicContrast: 0.5
  saturation: 0.5
cta: {}
layout_spectrum: 0.806743
name: Gaurav Nawathey
opengraph: {}
purpose: []
typography_spectrum: 0.792763
