typography_spectrum: 0.792763
color:
  brandColors:
    - '#0c0c0c'
    - '#ffe4b3'
    - '#c6af59'
    - '#836c48'
    - '#d8682a'
  brandStrength: 1
  lightness: 0.75
  rhythmicContrast: 0.5
  saturation: 0.5
opengraph: {}
layout_spectrum: 0.806743
analytics: {}
name: Gaurav Nawathey Photography
cta: {}
title: Commercial & Wildlife Photograper
description: 'into the forest I go, to loose my mind and find my soul'
purpose: []
