name: Gaurav Nawathey
favicon: null
layout_spectrum: 0
typography_spectrum: 0.71668
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0c0c'
    - '#ffe4b3'
    - '#c6af59'
    - '#836c48'
    - '#d8682a'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
